### ISSUE TITLE
[Feature Request] Ability to mute notifications from selected groupchats

### ISSUE THREAD

**Issue by rodneyrod** [QtGram/harbour-sailorgram#101]
This feature is common across other Telegram clients, just to prevent notifications every time someone posts to a groupchat.

**Comment by Dax89** [comment]
Aren't the already implemented notification settings?

**Comment by rodneyrod** [comment]
Not from what I can see in the warehouse version, doesn't seem to be a way to mute group chats, unless it's there and I've missed it.

**Comment by Dax89** [comment]
There is "Enable/Disable notifications" when you open a chat, in the attached page on the right

**Comment by rodneyrod** [comment]
@Dax89 I'll try and give that a go.

Also, when will this get uploaded to the Jolla Store? Warehouse has been doing odd things and crashes every so often so I might end up retiring that.

**Comment by rodneyrod** [comment]
You were right, found the setting, closing this issue

**Comment by Dax89** [comment]
Sailorgram is not allowed in the jolla store yet
