### ISSUE TITLE
Sailorgram is receiving wrong incorrect SMS code from Telegram. How to fix it?

### ISSUE THREAD

**Issue by serloz** [QtGram/harbour-sailorgram#95]
Sailorgram is receiving wrong incorrect SMS code from Telegram. How to fix it? Activation code from SMS (Telegram) is always incorrect. Please, have you got any idea about it? Thanks!

**Comment by z3ntu** [comment]
I just activated Sailorgram yesterday and the code sent to my other Telegram client(s) was correct.

**Comment by Dax89** [comment]
@serloz: Is two factor authentication active? Sailorgram doesn't support that yet

**Comment by serloz** [comment]
Thank you both for your answers! Two-factor authentication was active at first, then already was deactivated... Anyway, Telegram's support sent me a direct message code that definitely did work, so now I have Sailorgram working properly, great job by the way , it is a pleasure!

**Comment by Dax89** [comment]
Can I close this issue?

**Comment by serloz** [comment]
Of course, no problem, thanks!!!
