### ISSUE TITLE
adding chats

### ISSUE THREAD

**Issue by nauevg** [QtGram/harbour-sailorgram#97]
Hello.
I registered with desktop client. added one contact. It showed in Sailorgram (0.80.2). After that i added  chat (in desktop too with sended invait) and it not appeared in Sailorgram.
Also i can not find way to add chat.
How can i do it?

**Comment by Dax89** [comment]
Is it a supergroup or a channel?

**Comment by nauevg** [comment]
Not sure, i am new telegram user. Is it possible to find out from desktop client? Or only ask owner of that chat?

**Comment by Dax89** [comment]
I don't know, supergroups simply doesn't shows up on sailorgram (channels too)

**Comment by nauevg** [comment]
This means no any group chats works in sailorgram for current moment, right?

**Comment by Dax89** [comment]
Yes, standard groups works.
0.9 in in development, if eveything goes well it's possible to see some betas during the end of November

**Comment by nauevg** [comment]
Found out type of chat. As you mentioned - this is supergroup.
Thanks for answers. Will wait new versions.
